# Generated by Django 2.1.1 on 2018-09-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0002_auto_20180909_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(),
        ),
    ]
