# Generated by Django 2.1.1 on 2018-09-09 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0003_auto_20180909_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='comments',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 14, 45, 38, 222857, tzinfo=utc)),
        ),
    ]
