# Generated by Django 2.1.1 on 2018-09-09 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0004_auto_20180909_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 15, 4, 32, 260342, tzinfo=utc)),
        ),
    ]
