# Generated by Django 2.1.1 on 2018-09-11 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0006_auto_20180909_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='banned',
            new_name='is_banned',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='post_count',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='users',
            name='comment_count',
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='sample name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 11, 6, 9, 33, 439641, tzinfo=utc)),
        ),
    ]
