# Generated by Django 2.1.1 on 2018-09-14 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0009_auto_20180914_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 14, 15, 39, 4, 534388, tzinfo=utc)),
        ),
    ]
