# Generated by Django 2.1.1 on 2018-09-21 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0014_auto_20180919_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 21, 11, 14, 30, 380017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 21, 11, 14, 30, 381017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 21, 11, 14, 30, 381017, tzinfo=utc)),
        ),
    ]
